/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
      extend: {
          colors: {
              "surface-default": "var(--surface-default)",
              "surface-sunken": "var(--surface-sunken)",
              "surface-logo": "var(--surface-logo)",
              "surface-drop": "var(--surface-drop)",
              "bold-brand-default": "var(--bold-brand-default)",
              "bold-brand-subtle": "var(--bold-brand-subtle)",
              "bold-green-default": "var(--bold-green-default)",
              "bold-green-subtle": "var(--bold-green-subtle)",
              "bold-yellow-default": "var(--bold-yellow-default)",
              "bold-yellow-subtle": "var(--bold-yellow-subtle)",
              "bold-error-default": "var(--bold-error-default)",
              "bold-error-subtle": "var(--bold-error-subtle)",
              "bold-orange-default": "var(--bold-orange-default)",
              "bold-orange-subtle": "var(--bold-orange-subtle)",
              "bold-cyan-default": "var(--bold-cyan-default)",
              "bold-cyan-subtle": "var(--bold-cyan-subtle)",
              "bold-blue-default": "var(--bold-blue-default)",
              "bold-blue-subtle": "var(--bold-blue-subtle)",
              "tint-brand-default": "var(--tint-brand-default)",
              "tint-brand-subtle": "var(--tint-brand-subtle)",
              "tint-yellow-default": "var(--tint-yellow-default)",
              "tint-yellow-subtle": "var(--tint-yellow-subtle)",
              "tint-green-default": "var(--tint-green-default)",
              "tint-green-subtle": "var(--tint-green-subtle)",
              "tint-error-default": "var(--tint-error-default)",
              "tint-error-subtle": "var(--tint-error-subtle)",
              "tint-orange-default": "var(--tint-orange-default)",
              "tint-orange-subtle": "var(--tint-orange-subtle)",
              "tint-cyan-default": "var(--tint-cyan-default)",
              "tint-cyan-subtle": "var(--tint-cyan-subtle)",
              "tint-blue-default": "var(--tint-blue-default)",
              "tint-blue-subtle": "var(--tint-blue-subtle)",
              "text-white": "var(--text-white)",
              "text-bolder": "var(--text-bolder)",
              "text-subtle": "var(--text-subtle)",
              "text-subtler": "var(--text-subtler)",
              "text-subtlest": "var(--text-subtlest)",
              "text-primary": "var(--text-primary)",
              "text-primary-tint": "var(--text-primary-tint)",
              "text-secondary": "var(--text-secondary)",
              "text-error": "var(--text-error)",
              "text-success": "var(--text-success)",
              "text-warning": "var(--text-warning)",
              "text-info": "var(--text-info)",
              "text-discovery": "var(--text-discovery)",
              "icon-neutral": "var(--icon-neutral)",
              "icon-white": "var(--icon-white)",
              "icon-bolder": "var(--icon-bolder)",
              "icon-subtle": "var(--icon-subtle)",
              "icon-subtler": "var(--icon-subtler)",
              "icon-subtlest": "var(--icon-subtlest)",
              "icon-primary": "var(--icon-primary)",
              "icon-primary-tint": "var(--icon-primary-tint)",
              "icon-secondary": "var(--icon-secondary)",
              "icon-error": "var(--icon-error)",
              "icon-success": "var(--icon-success)",
              "icon-warning": "var(--icon-warning)",
              "icon-info": "var(--icon-info)",
              "icon-discovery": "var(--icon-discovery)",
              "line-default": "var(--line-default)",
              "line-surface": "var(--line-surface)",
              "line-white": "var(--line-white)",
              "line-brand": "var(--line-brand)",
              "line-brand-tint": "var(--line-brand-tint)",
              "line-secodary": "var(--line-secodary)",
              "line-success": "var(--line-success)",
              "line-error": "var(--line-error)",
              "line-warning": "var(--line-warning)",
              "line-info": "var(--line-info)",
              "line-discovery": "var(--line-discovery)",
              "form-default": "var(--form-default)",
              "form-hov": "var(--form-hov)",
              "alpha-0": "var(--alpha-0)",
              "alpha-1": "var(--alpha-1)",
              "alpha-2": "var(--alpha-2)",
              "alpha-3": "var(--alpha-3)",
              "alpha-4": "var(--alpha-4)",
              "alpha-5": "var(--alpha-5)",
              "alpha-6": "var(--alpha-6)",
              "alpha-7": "var(--alpha-7)",
              "alpha-8": "var(--alpha-8)",
              "alpha-9": "var(--alpha-9)",
              "shadow-0": "var(--shadow-0)",
              "shadow-1": "var(--shadow-1)",
              "shadow-2": "var(--shadow-2)",
              "shadow-3": "var(--shadow-3)",
              "shadow-4": "var(--shadow-4)",
              "shadow-5": "var(--shadow-5)",
              "shadow-6": "var(--shadow-6)",
              "shadow-7": "var(--shadow-7)",
              "shadow-8": "var(--shadow-8)",
              "shadow-9": "var(--shadow-9)",
          },
          fontFamily: {
              inter: ["Inter", "sans-serif"],
              poppins: ["Poppins", "serif"],
          },
          borderWidth: {
            1: ".0938rem",
        },
        letterSpacing: {
                'custom': '0.2px', 
                'custom-wide': '-0.2px',  
        }
      },
  },

};
